"""
AI-powered market analyzer using DeepSeek.

Reads a market question + current state and returns a structured
trading recommendation with confidence and reasoning.

Tries the local Ollama instance first (free, no rate limits),
falls back to the DeepSeek API if Ollama is unavailable.
"""

import concurrent.futures
import hashlib
import json
import logging
import os
import re
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, Optional

DEEPSEEK_API_KEY = os.environ.get("DEEPSEEK_API_KEY", "")
LLM_LOG_DIR = Path(os.environ.get('LLM_LOG_DIR', Path(__file__).resolve().parent.parent / 'logs'))
OLLAMA_BASE = "http://localhost:11434"
OLLAMA_MODEL = "llama3.2:3b"
DEEPSEEK_API_BASE = "https://api.deepseek.com/v1"
DEEPSEEK_MODEL = "deepseek-chat"

# Path to calibration table (generated by scripts/analyze_calibration.py)
_CALIBRATION_TABLE_PATH = Path(__file__).resolve().parent.parent / "data" / "calibration_table.json"


def _build_calibration_note() -> str:
    """
    Load the calibration table and format it as a concise prompt block.

    The calibration table tells the AI how systematically biased the Manifold
    crowd is at each probability level, measured over 1,000+ resolved markets.
    This gives the AI a data-driven prior to apply before reasoning about the
    specific market — rather than naively trusting the crowd probability.

    Returns an empty string if the table file doesn't exist yet (first run
    before harvest_resolved.py has been run, or on a fresh server).
    """
    if not _CALIBRATION_TABLE_PATH.exists():
        return ""
    try:
        with open(_CALIBRATION_TABLE_PATH) as f:
            data = json.load(f)
        buckets = data.get("buckets", [])
        if not buckets:
            return ""
        lines = [
            "Crowd calibration (measured over 1,000+ resolved Manifold markets):",
            "  Bucket      Crowd says  Actual YES rate  Bias",
        ]
        for b in buckets:
            if not b.get("reliable"):
                continue
            low  = int(b["bucket_low"]  * 100)
            high = int(b["bucket_high"] * 100)
            crowd = int(b["crowd_midpoint"] * 100)
            actual = int((b["actual_yes_rate"] or 0) * 100)
            bias  = (b["bias"] or 0) * 100
            bias_str = f"{bias:+.0f}pp"
            note = " ← MOST BIASED" if abs(bias) >= 15 else (" ← significant" if abs(bias) >= 10 else "")
            lines.append(f"  {low:3d}–{high:3d}%   {crowd:3d}%       {actual:3d}%            {bias_str}{note}")
        lines.append(
            "Use these corrections: if a market is at 65%, history says treat it as ~47% YES. "
            "Adjust your estimated_true_probability accordingly before deciding YES/NO/SKIP. "
            "Note: this correction applies primarily to politics markets; "
            "sports and economics markets are well-calibrated at all buckets and need no adjustment."
        )
        return "\n".join(lines)
    except Exception as e:
        logger.warning("Could not load calibration table: %s", e)
        return ""


_STRATEGY_WEIGHTS_PATH = Path(__file__).resolve().parent.parent / "data" / "strategy_weights.json"


def _build_performance_note() -> str:
    """
    Build a compact prompt block summarising per-strategy reliability weights.

    Tells the AI which statistical strategies have been historically accurate
    so it can calibrate how much to trust the stat signal when blending.

    Returns empty string if the weights file is absent or has no data yet.
    """
    if not _STRATEGY_WEIGHTS_PATH.exists():
        return ""
    try:
        with open(_STRATEGY_WEIGHTS_PATH) as f:
            data = json.load(f)
    except Exception:
        return ""

    weights = data.get("weights", {})
    sample_count = data.get("sample_count", 0)
    threshold = data.get("min_samples_threshold", 10)

    if not weights or sample_count < threshold:
        return ""

    lines = [f"Strategy reliability (from {sample_count} resolved trades):"]
    for strat, w in sorted(weights.items()):
        if w >= 1.10:
            note = "↑ above-average accuracy"
        elif w <= 0.80:
            note = "↓ below-average accuracy"
        else:
            note = "≈ average accuracy"
        lines.append(f"  {strat}: weight={w:.2f}  ({note})")
    lines.append(
        "Higher-weight strategies have historically called direction correctly more often. "
        "Give their signal more weight when they agree with your analysis."
    )
    return "\n".join(lines)


# Built once at import time. Each cron process picks up the latest table.
_CALIBRATION_NOTE_MAX_LEN = 2000
try:
    _raw_calibration_note = _build_calibration_note()
    if len(_raw_calibration_note) > _CALIBRATION_NOTE_MAX_LEN:
        # logger is not yet defined at module level here — use print
        print(f"[ai_analyzer] calibration note truncated from {len(_raw_calibration_note)} to {_CALIBRATION_NOTE_MAX_LEN} chars")
        _CALIBRATION_NOTE = _raw_calibration_note[:_CALIBRATION_NOTE_MAX_LEN]
    else:
        _CALIBRATION_NOTE = _raw_calibration_note
except (json.JSONDecodeError, KeyError):
    _CALIBRATION_NOTE = ''

try:
    _PERFORMANCE_NOTE = _build_performance_note()
except Exception:
    _PERFORMANCE_NOTE = ''

# Maximum size for llm_calls.jsonl before rotation (100 MB)
LLM_LOG_MAX_BYTES = 100 * 1024 * 1024
# Number of rotated backup files to keep
LLM_LOG_BACKUP_COUNT = 3

logger = logging.getLogger(__name__)

SYSTEM_PROMPT = """You are an expert prediction market analyst. Your job is to assess whether a market's current probability is accurate or mispriced.

A prediction market works like this:
- A question has a YES or NO outcome that will resolve in the future
- The current probability (0-100%) reflects what the crowd believes
- If you think the crowd is WRONG and the real probability is HIGHER than shown, bet YES
- If you think the crowd is WRONG and the real probability is LOWER than shown, bet NO
- If the probability looks roughly correct, do NOT trade

Be a contrarian when the evidence supports it. Consider:
- Is the question well-defined and likely to resolve clearly?
- Does the current probability seem too high or too low given what you know?
- Are there reasons the crowd might be systematically biased?
- How confident are you in your assessment?

Always respond with valid JSON only. No markdown, no extra text."""

# Stable identifier for the system prompt; recomputed once at import time.
# Recording the hash instead of the full text avoids duplicating the static
# prompt on every log record while still allowing offline verification that
# the prompt has not changed between runs.
SYSTEM_PROMPT_SHA256 = hashlib.sha256(SYSTEM_PROMPT.encode()).hexdigest()

ANALYSIS_PROMPT = """Analyze this prediction market:

Question: {question}
Current probability: {probability:.0%}
Trading volume: ${volume:.0f}
Liquidity: ${liquidity:.0f}
Close date: {close_date}

Additional context:
{context}

{calibration_note}

{performance_note}

Respond with this exact JSON structure:
{{
  "recommendation": "YES" or "NO" or "SKIP",
  "confidence": <float 0.0 to 1.0>,
  "estimated_true_probability": <float 0.0 to 1.0>,
  "reasoning": "<1-2 sentence explanation>",
  "risk_factors": "<brief note on what could make this trade wrong>"
}}

Only recommend YES or NO if you have genuine conviction the market is mispriced by at least 10 percentage points. Otherwise use SKIP."""


def _rotate_log_if_needed(log_path: Path) -> None:
    """
    Rotate log_path if it exceeds LLM_LOG_MAX_BYTES.

    Keeps up to LLM_LOG_BACKUP_COUNT numbered backups:
      llm_calls.jsonl.1  (most recent previous)
      llm_calls.jsonl.2
      llm_calls.jsonl.3  (oldest kept)

    The oldest backup beyond the count is deleted.
    """
    if not log_path.exists():
        return
    if log_path.stat().st_size < LLM_LOG_MAX_BYTES:
        return

    # Shift existing backups: .2 -> .3, .1 -> .2 (high to low to avoid clobbering)
    for i in range(LLM_LOG_BACKUP_COUNT, 1, -1):
        src = log_path.parent / (log_path.name + f".{i - 1}")
        older = log_path.parent / (log_path.name + f".{i}")
        if src.exists():
            if older.exists():
                older.unlink()
            src.rename(older)

    # Rename the active log to .1
    dest = log_path.parent / (log_path.name + ".1")
    if dest.exists():
        dest.unlink()
    log_path.rename(dest)


def _log_llm_call(
    model: str,
    system_prompt_hash: str,
    market_id: str,
    parsed_output: Optional[Dict] = None,
    source: str = "unknown",
    latency_ms: Optional[float] = None,
    ollama_timed_out: bool = False,
) -> None:
    """Append a JSONL record for every LLM call (for future distillation).

    We deliberately do NOT log the full system prompt (it is static and
    bloats every record) nor the full user prompt (it may contain market
    data whose long-term persistence requires compliance review).

    For the same compliance reasons we also do NOT log the raw LLM response
    verbatim: the model may echo or summarise market data supplied in the
    prompt, so the raw response carries the same sensitivity as the prompt
    itself.  Instead we store only:
      - system_prompt_sha256: allows offline verification that the prompt
        has not changed between runs without duplicating its text.
      - market_id: a stable, non-sensitive identifier that can be joined
        against the market database to reconstruct the prompt if needed.
      - parsed_output: the structured fields extracted from the response
        (recommendation, confidence, etc.) which do not reproduce raw
        market data.

    NOTE: Logging of the raw LLM response (including any chain-of-thought)
    is intentionally omitted pending a compliance review.  The model may
    echo or summarise market data from the user prompt, so storing the raw
    response verbatim raises the same concerns as storing the prompt itself.
    See the issue comment for context.
    """
    try:
        LLM_LOG_DIR.mkdir(parents=True, exist_ok=True)

        record = {
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "model": model,
            "source": source,                        # "ollama" or "deepseek_api"
            "latency_ms": round(latency_ms, 1) if latency_ms is not None else None,
            "ollama_timed_out": ollama_timed_out,    # True = stuck runner detected
            "system_prompt_sha256": system_prompt_hash,
            "market_id": market_id,
            # raw_response and chain_of_thought are intentionally excluded
            # pending compliance review.  See docstring above.
            "parsed_output": parsed_output,
        }

        log_path = LLM_LOG_DIR / "llm_calls.jsonl"
        _rotate_log_if_needed(log_path)

        with open(log_path, "a", encoding="utf-8") as f:
            f.write(json.dumps(record, ensure_ascii=False) + "\n")
    except Exception as e:
        print(f'[llm_log] warning: {e}', file=sys.stderr)
        logger.warning('[llm_log] warning: %s', e)


def _call_ollama(prompt: str, meta: Optional[dict] = None) -> Optional[str]:
    """
    Call local Ollama instance using streaming.

    We stream (stream=True) instead of waiting for the full response in one shot
    (stream=False) for a critical reason: when the Ollama runner process is stuck
    in a spin loop (symptom: 700%+ CPU, no useful output), it accepts the TCP
    connection but never writes the first response byte. With stream=False the
    read_timeout is the only protection — it had to be set to 60s to allow normal
    80s generation, meaning a stuck runner blocks for 60s per market (180s for 3).

    With streaming, the connect timeout (5s) catches an unreachable Ollama, and a
    separate FIRST_TOKEN_TIMEOUT (20s) catches a stuck runner: healthy Ollama sends
    the first token within a few seconds of starting generation; a hung process
    never does. Once the first token arrives we read the rest with a generous
    per-chunk timeout since generation can legitimately take 80-90s on CPU.

    With llama3.2:3b at ~9 tok/s, first token arrives in <2s and a full
    300-token response completes in ~35s — well within both timeout bounds.

    meta: optional dict; if provided, sets meta['timed_out']=True on timeout
    so the caller can distinguish a stuck runner from other failures.
    """
    FIRST_TOKEN_TIMEOUT = 40   # seconds — cold model load for 3b takes ~15-20s; warm is <2s
    PER_CHUNK_TIMEOUT   = 60   # seconds per subsequent chunk — 3b finishes in ~35s at 9 tok/s
    try:
        import requests
        response = requests.post(
            f"{OLLAMA_BASE}/api/generate",
            json={
                "model": OLLAMA_MODEL,
                "prompt": f"{SYSTEM_PROMPT}\n\n{prompt}",
                "stream": True,
                "keep_alive": "2h",  # keep model resident between hourly cron runs
                "options": {"temperature": 0.3}
            },
            timeout=(5, FIRST_TOKEN_TIMEOUT),  # connect=5s, first-byte=20s
            stream=True,
        )
        if response.status_code != 200:
            return None

        full_text = []
        first_chunk = True
        for raw_line in response.iter_lines(chunk_size=None):
            if not raw_line:
                continue
            try:
                chunk = json.loads(raw_line)
            except (json.JSONDecodeError, ValueError):
                continue
            full_text.append(chunk.get("response", ""))
            if chunk.get("done"):
                break
            if first_chunk:
                # After the first token arrives, extend the socket timeout so
                # long CPU inference can finish without hitting the 20s deadline.
                response.raw._fp.fp.raw._sock.settimeout(PER_CHUNK_TIMEOUT)
                first_chunk = False

        return "".join(full_text) if full_text else None

    except Exception as e:
        import requests as _req
        if isinstance(e, (_req.exceptions.Timeout, _req.exceptions.ReadTimeout)):
            if meta is not None:
                meta['timed_out'] = True
    return None


def _call_deepseek_api(prompt: str) -> Optional[str]:
    """Call DeepSeek API."""
    if not DEEPSEEK_API_KEY:
        return None
    try:
        import requests
        response = requests.post(
            f"{DEEPSEEK_API_BASE}/chat/completions",
            headers={
                "Authorization": f"Bearer {DEEPSEEK_API_KEY}",
                "Content-Type": "application/json"
            },
            json={
                "model": DEEPSEEK_MODEL,
                "messages": [
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user", "content": prompt}
                ],
                "temperature": 0.3,
                "max_tokens": 400
            },
            timeout=30
        )
        if response.status_code == 200:
            return response.json()["choices"][0]["message"]["content"]
    except Exception:
        pass
    return None


def _parse_response(raw: str) -> Optional[Dict]:
    """Extract JSON from model response, handling reasoning tags."""
    if not raw:
        return None

    # Strip <think>...</think> blocks from reasoning models
    raw = re.sub(r'<think>.*?</think>', '', raw, flags=re.DOTALL).strip()

    # Find the JSON object
    match = re.search(r'\{.*\}', raw, re.DOTALL)
    if not match:
        return None

    try:
        parsed = json.loads(match.group())

        recommendation = parsed.get("recommendation", "SKIP").upper()
        if recommendation not in ("YES", "NO", "SKIP"):
            recommendation = "SKIP"

        confidence = float(parsed.get("confidence", 0.0))
        confidence = max(0.0, min(1.0, confidence))

        # If SKIP, force confidence to 0
        if recommendation == "SKIP":
            confidence = 0.0

        return {
            "recommendation": recommendation,
            "confidence": round(confidence, 3),
            "estimated_true_probability": round(
                float(parsed.get("estimated_true_probability", 0.5)), 3
            ),
            "reasoning": str(parsed.get("reasoning", ""))[:300],
            "risk_factors": str(parsed.get("risk_factors", ""))[:200],
        }
    except (json.JSONDecodeError, ValueError, TypeError):
        return None


def analyze_market(market: Dict) -> Optional[Dict]:
    """
    Run AI analysis on a single market.

    Args:
        market: Market dict from Manifold API (must have at least 'question' and 'probability')

    Returns:
        Dict with keys: recommendation, confidence, estimated_true_probability,
        reasoning, risk_factors, source ("ollama" or "deepseek_api")
        Returns None if both backends are unavailable.
    """
    question = market.get("question", "")
    probability = market.get("probability", 0.5)
    volume = market.get("volume", 0)
    liquidity = market.get("totalLiquidity", market.get("liquidity", 0))
    market_id = market.get("id") or ""

    if not market_id:
        logger.warning("analyze_market called with market missing id field")
        market_id = "UNKNOWN"

    # Format close date
    close_time_ms = market.get("closeTime")
    if close_time_ms:
        close_date = datetime.fromtimestamp(
            close_time_ms / 1000, tz=timezone.utc
        ).strftime("%Y-%m-%d")
    else:
        close_date = "unknown"

    # Build extra context from available fields
    context_parts = []
    creator = market.get("creatorName") or market.get("creatorUsername")
    if creator:
        context_parts.append(f"Created by: {creator}")
    description = market.get("description") or market.get("textDescription", "")
    if description and isinstance(description, str) and len(description) > 10:
        context_parts.append(f"Description: {description[:300]}")
    if not context_parts:
        context_parts.append("No additional context available.")

    prompt = ANALYSIS_PROMPT.format(
        question=question,
        probability=probability,
        volume=volume,
        liquidity=liquidity,
        close_date=close_date,
        context="\n".join(context_parts),
        calibration_note=_CALIBRATION_NOTE,
        performance_note=_PERFORMANCE_NOTE,
    )

    # Try Ollama first (free), then DeepSeek API.
    # Track latency and whether Ollama timed out (stuck runner vs just down).
    ollama_meta: dict = {}
    t0 = time.monotonic()
    raw = _call_ollama(prompt, meta=ollama_meta)
    source = "ollama"
    ollama_timed_out = ollama_meta.get('timed_out', False)

    if raw is None:
        raw = _call_deepseek_api(prompt)
        source = "deepseek_api"

    latency_ms = (time.monotonic() - t0) * 1000

    if raw is None:
        return None

    result = _parse_response(raw)

    # Log after parsing so parsed_output is available.
    # raw_response is intentionally not forwarded to _log_llm_call — see
    # that function's docstring for the compliance rationale.
    model = OLLAMA_MODEL if source == "ollama" else DEEPSEEK_MODEL
    _log_llm_call(
        model, SYSTEM_PROMPT_SHA256, market_id,
        parsed_output=result,
        source=source,
        latency_ms=latency_ms,
        ollama_timed_out=ollama_timed_out,
    )

    if result:
        result["source"] = source
        result["market_id"] = market_id
    return result


def batch_analyze(markets: list, max_markets: int = 20, delay: float = 1.0, per_market_timeout: float = 90.0) -> Dict[str, Dict]:
    """
    Analyze a batch of markets.

    Args:
        markets: List of market dicts
        max_markets: Cap to avoid rate limits / long runtimes
        delay: Seconds between calls (be polite to APIs)
        per_market_timeout: Max seconds to spend on a single market before skipping it.
            Each market analysis is submitted to a ThreadPoolExecutor and cancelled
            (skipped) if it does not complete within this deadline.

    Returns:
        Dict keyed by market_id -> analysis result
    """
    results = {}
    count = 0
    # Wall-clock deadline for the entire batch. Each market gets per_market_timeout,
    # but we also enforce a total budget so a slow first market can't eat all slots.
    batch_deadline = time.monotonic() + per_market_timeout * max(len(markets[:max_markets]), 1) + 10

    for market in markets[:max_markets]:
        market_id = market.get("id", "")
        if not market_id:
            continue

        if time.monotonic() > batch_deadline:
            logger.warning("AI batch global timeout reached — stopping early after %d results.", len(results))
            break

        result = None
        # Do NOT use `with ThreadPoolExecutor` here. The context manager calls
        # shutdown(wait=True) on exit — even when a TimeoutError is raised — which
        # blocks the main thread until the background thread's requests.post() call
        # finishes. That means the actual hang is future_timeout + requests_timeout
        # (up to 150s per market, 450s for 3 markets), busting the 300s cron budget.
        # Instead, shut down with wait=False so the background thread is abandoned
        # immediately after timeout and the loop moves on.
        executor = concurrent.futures.ThreadPoolExecutor(max_workers=1)
        future = executor.submit(analyze_market, market)
        try:
            result = future.result(timeout=per_market_timeout)
        except concurrent.futures.TimeoutError:
            logger.warning(
                "AI analysis timed out after %.1fs for market %s (%s) — skipping.",
                per_market_timeout,
                market_id,
                market.get("question", "")[:60],
            )
            result = None
        except Exception as exc:
            logger.warning(
                "AI analysis raised an unexpected error for market %s: %s — skipping.",
                market_id,
                exc,
            )
            result = None
        finally:
            # wait=False: do not block on the background thread. It will clean up
            # on its own once the underlying requests call completes or errors.
            executor.shutdown(wait=False)

        if result:
            results[market_id] = result
            rec = result["recommendation"]
            conf = result["confidence"]
            source = result["source"]
            print(f"  AI [{source}] {market.get('question', '')[:60]}...")
            print(f"       → {rec} ({conf:.0%} confidence): {result['reasoning'][:80]}")
            # DeepSeek API fallback always enforces 2s regardless of caller-supplied delay.
            # This is intentional: delay=0 is safe for Ollama (CPU-bound) but not for a paid API.
            effective_delay = 2.0 if source == "deepseek_api" else delay
        else:
            print(f"  AI analysis unavailable for {market_id}")
            effective_delay = delay

        count += 1
        if count < len(markets[:max_markets]):
            time.sleep(effective_delay)

    return results
