"""
AI-powered market analyzer using DeepSeek.

Reads a market question + current state and returns a structured
trading recommendation with confidence and reasoning.

Tries the local Ollama instance first (free, no rate limits),
falls back to the DeepSeek API if Ollama is unavailable.
"""

import concurrent.futures
import hashlib
import json
import logging
import os
import re
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, Optional

DEEPSEEK_API_KEY = os.environ.get("DEEPSEEK_API_KEY", "")
LLM_LOG_DIR = Path(os.environ.get('LLM_LOG_DIR', Path(__file__).resolve().parent.parent / 'logs'))
OLLAMA_BASE = "http://localhost:11434"
OLLAMA_MODEL = "deepseek-r1:14b"
DEEPSEEK_API_BASE = "https://api.deepseek.com/v1"
DEEPSEEK_MODEL = "deepseek-chat"

# Path to calibration table (generated by scripts/analyze_calibration.py)
_CALIBRATION_TABLE_PATH = Path(__file__).resolve().parent.parent / "data" / "calibration_table.json"


def _build_calibration_note() -> str:
    """
    Load the calibration table and format it as a concise prompt block.

    The calibration table tells the AI how systematically biased the Manifold
    crowd is at each probability level, measured over 1,000+ resolved markets.
    This gives the AI a data-driven prior to apply before reasoning about the
    specific market — rather than naively trusting the crowd probability.

    Returns an empty string if the table file doesn't exist yet (first run
    before harvest_resolved.py has been run, or on a fresh server).
    """
    if not _CALIBRATION_TABLE_PATH.exists():
        return ""
    try:
        with open(_CALIBRATION_TABLE_PATH) as f:
            data = json.load(f)
        buckets = data.get("buckets", [])
        if not buckets:
            return ""
        lines = [
            "Crowd calibration (measured over 1,000+ resolved Manifold markets):",
            "  Bucket      Crowd says  Actual YES rate  Bias",
        ]
        for b in buckets:
            if not b.get("reliable"):
                continue
            low  = int(b["bucket_low"]  * 100)
            high = int(b["bucket_high"] * 100)
            crowd = int(b["crowd_midpoint"] * 100)
            actual = int((b["actual_yes_rate"] or 0) * 100)
            bias  = (b["bias"] or 0) * 100
            bias_str = f"{bias:+.0f}pp"
            note = " ← MOST BIASED" if abs(bias) >= 15 else (" ← significant" if abs(bias) >= 10 else "")
            lines.append(f"  {low:3d}–{high:3d}%   {crowd:3d}%       {actual:3d}%            {bias_str}{note}")
        lines.append(
            "Use these corrections: if a market is at 65%, history says treat it as ~47% YES. "
            "Adjust your estimated_true_probability accordingly before deciding YES/NO/SKIP."
        )
        return "\n".join(lines)
    except Exception as e:
        logger.warning("Could not load calibration table: %s", e)
        return ""


# Built once at import time. Each cron process picks up the latest table.
try:
    _CALIBRATION_NOTE = _build_calibration_note()
except (json.JSONDecodeError, KeyError):
    _CALIBRATION_NOTE = ''

# Maximum size for llm_calls.jsonl before rotation (100 MB)
LLM_LOG_MAX_BYTES = 100 * 1024 * 1024
# Number of rotated backup files to keep
LLM_LOG_BACKUP_COUNT = 3

logger = logging.getLogger(__name__)

SYSTEM_PROMPT = """You are an expert prediction market analyst. Your job is to assess whether a market's current probability is accurate or mispriced.

A prediction market works like this:
- A question has a YES or NO outcome that will resolve in the future
- The current probability (0-100%) reflects what the crowd believes
- If you think the crowd is WRONG and the real probability is HIGHER than shown, bet YES
- If you think the crowd is WRONG and the real probability is LOWER than shown, bet NO
- If the probability looks roughly correct, do NOT trade

Be a contrarian when the evidence supports it. Consider:
- Is the question well-defined and likely to resolve clearly?
- Does the current probability seem too high or too low given what you know?
- Are there reasons the crowd might be systematically biased?
- How confident are you in your assessment?

Always respond with valid JSON only. No markdown, no extra text."""

# Stable identifier for the system prompt; recomputed once at import time.
# Recording the hash instead of the full text avoids duplicating the static
# prompt on every log record while still allowing offline verification that
# the prompt has not changed between runs.
SYSTEM_PROMPT_SHA256 = hashlib.sha256(SYSTEM_PROMPT.encode()).hexdigest()

ANALYSIS_PROMPT = """Analyze this prediction market:

Question: {question}
Current probability: {probability:.0%}
Trading volume: ${volume:.0f}
Liquidity: ${liquidity:.0f}
Close date: {close_date}

Additional context:
{context}

{calibration_note}

Respond with this exact JSON structure:
{{
  "recommendation": "YES" or "NO" or "SKIP",
  "confidence": <float 0.0 to 1.0>,
  "estimated_true_probability": <float 0.0 to 1.0>,
  "reasoning": "<1-2 sentence explanation>",
  "risk_factors": "<brief note on what could make this trade wrong>"
}}

Only recommend YES or NO if you have genuine conviction the market is mispriced by at least 10 percentage points. Otherwise use SKIP."""


def _rotate_log_if_needed(log_path: Path) -> None:
    """
    Rotate log_path if it exceeds LLM_LOG_MAX_BYTES.

    Keeps up to LLM_LOG_BACKUP_COUNT numbered backups:
      llm_calls.jsonl.1  (most recent previous)
      llm_calls.jsonl.2
      llm_calls.jsonl.3  (oldest kept)

    The oldest backup beyond the count is deleted.
    """
    if not log_path.exists():
        return
    if log_path.stat().st_size < LLM_LOG_MAX_BYTES:
        return

    # Shift existing backups: .2 -> .3, .1 -> .2 (high to low to avoid clobbering)
    for i in range(LLM_LOG_BACKUP_COUNT, 1, -1):
        src = log_path.parent / (log_path.name + f".{i - 1}")
        older = log_path.parent / (log_path.name + f".{i}")
        if src.exists():
            if older.exists():
                older.unlink()
            src.rename(older)

    # Rename the active log to .1
    dest = log_path.parent / (log_path.name + ".1")
    if dest.exists():
        dest.unlink()
    log_path.rename(dest)


def _log_llm_call(
    model: str,
    system_prompt_hash: str,
    market_id: str,
    parsed_output: Optional[Dict] = None,
) -> None:
    """Append a JSONL record for every LLM call (for future distillation).

    We deliberately do NOT log the full system prompt (it is static and
    bloats every record) nor the full user prompt (it may contain market
    data whose long-term persistence requires compliance review).

    For the same compliance reasons we also do NOT log the raw LLM response
    verbatim: the model may echo or summarise market data supplied in the
    prompt, so the raw response carries the same sensitivity as the prompt
    itself.  Instead we store only:
      - system_prompt_sha256: allows offline verification that the prompt
        has not changed between runs without duplicating its text.
      - market_id: a stable, non-sensitive identifier that can be joined
        against the market database to reconstruct the prompt if needed.
      - parsed_output: the structured fields extracted from the response
        (recommendation, confidence, etc.) which do not reproduce raw
        market data.

    NOTE: Logging of the raw LLM response (including any chain-of-thought)
    is intentionally omitted pending a compliance review.  The model may
    echo or summarise market data from the user prompt, so storing the raw
    response verbatim raises the same concerns as storing the prompt itself.
    See the issue comment for context.
    """
    try:
        LLM_LOG_DIR.mkdir(parents=True, exist_ok=True)

        record = {
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "model": model,
            "system_prompt_sha256": system_prompt_hash,
            "market_id": market_id,
            # raw_response and chain_of_thought are intentionally excluded
            # pending compliance review.  See docstring above.
            "parsed_output": parsed_output,
        }

        log_path = LLM_LOG_DIR / "llm_calls.jsonl"
        _rotate_log_if_needed(log_path)

        with open(log_path, "a", encoding="utf-8") as f:
            f.write(json.dumps(record, ensure_ascii=False) + "\n")
    except Exception as e:
        print(f'[llm_log] warning: {e}', file=sys.stderr)
        logger.warning('[llm_log] warning: %s', e)


def _call_ollama(prompt: str) -> Optional[str]:
    """Call local Ollama instance."""
    try:
        import requests
        response = requests.post(
            f"{OLLAMA_BASE}/api/generate",
            json={
                "model": OLLAMA_MODEL,
                "prompt": f"{SYSTEM_PROMPT}\n\n{prompt}",
                "stream": False,
                "options": {"temperature": 0.3}
            },
            timeout=60
        )
        if response.status_code == 200:
            return response.json().get("response", "")
    except Exception:
        pass
    return None


def _call_deepseek_api(prompt: str) -> Optional[str]:
    """Call DeepSeek API."""
    if not DEEPSEEK_API_KEY:
        return None
    try:
        import requests
        response = requests.post(
            f"{DEEPSEEK_API_BASE}/chat/completions",
            headers={
                "Authorization": f"Bearer {DEEPSEEK_API_KEY}",
                "Content-Type": "application/json"
            },
            json={
                "model": DEEPSEEK_MODEL,
                "messages": [
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user", "content": prompt}
                ],
                "temperature": 0.3,
                "max_tokens": 400
            },
            timeout=30
        )
        if response.status_code == 200:
            return response.json()["choices"][0]["message"]["content"]
    except Exception:
        pass
    return None


def _parse_response(raw: str) -> Optional[Dict]:
    """Extract JSON from model response, handling reasoning tags."""
    if not raw:
        return None

    # Strip <think>...</think> blocks from reasoning models
    raw = re.sub(r'<think>.*?</think>', '', raw, flags=re.DOTALL).strip()

    # Find the JSON object
    match = re.search(r'\{.*\}', raw, re.DOTALL)
    if not match:
        return None

    try:
        parsed = json.loads(match.group())

        recommendation = parsed.get("recommendation", "SKIP").upper()
        if recommendation not in ("YES", "NO", "SKIP"):
            recommendation = "SKIP"

        confidence = float(parsed.get("confidence", 0.0))
        confidence = max(0.0, min(1.0, confidence))

        # If SKIP, force confidence to 0
        if recommendation == "SKIP":
            confidence = 0.0

        return {
            "recommendation": recommendation,
            "confidence": round(confidence, 3),
            "estimated_true_probability": round(
                float(parsed.get("estimated_true_probability", 0.5)), 3
            ),
            "reasoning": str(parsed.get("reasoning", ""))[:300],
            "risk_factors": str(parsed.get("risk_factors", ""))[:200],
        }
    except (json.JSONDecodeError, ValueError, TypeError):
        return None


def analyze_market(market: Dict) -> Optional[Dict]:
    """
    Run AI analysis on a single market.

    Args:
        market: Market dict from Manifold API (must have at least 'question' and 'probability')

    Returns:
        Dict with keys: recommendation, confidence, estimated_true_probability,
        reasoning, risk_factors, source ("ollama" or "deepseek_api")
        Returns None if both backends are unavailable.
    """
    question = market.get("question", "")
    probability = market.get("probability", 0.5)
    volume = market.get("volume", 0)
    liquidity = market.get("totalLiquidity", market.get("liquidity", 0))
    market_id = market.get("id") or ""

    if not market_id:
        logger.warning("analyze_market called with market missing id field")
        market_id = "UNKNOWN"

    # Format close date
    close_time_ms = market.get("closeTime")
    if close_time_ms:
        close_date = datetime.fromtimestamp(
            close_time_ms / 1000, tz=timezone.utc
        ).strftime("%Y-%m-%d")
    else:
        close_date = "unknown"

    # Build extra context from available fields
    context_parts = []
    creator = market.get("creatorName") or market.get("creatorUsername")
    if creator:
        context_parts.append(f"Created by: {creator}")
    description = market.get("description") or market.get("textDescription", "")
    if description and isinstance(description, str) and len(description) > 10:
        context_parts.append(f"Description: {description[:300]}")
    if not context_parts:
        context_parts.append("No additional context available.")

    prompt = ANALYSIS_PROMPT.format(
        question=question,
        probability=probability,
        volume=volume,
        liquidity=liquidity,
        close_date=close_date,
        context="\n".join(context_parts),
        calibration_note=_CALIBRATION_NOTE,
    )

    # Try Ollama first (free), then DeepSeek API
    raw = _call_ollama(prompt)
    source = "ollama"
    if raw is None:
        raw = _call_deepseek_api(prompt)
        source = "deepseek_api"

    if raw is None:
        return None

    result = _parse_response(raw)

    # Log after parsing so parsed_output is available.
    # raw_response is intentionally not forwarded to _log_llm_call — see
    # that function's docstring for the compliance rationale.
    model = OLLAMA_MODEL if source == "ollama" else DEEPSEEK_MODEL
    _log_llm_call(model, SYSTEM_PROMPT_SHA256, market_id, parsed_output=result)

    if result:
        result["source"] = source
        result["market_id"] = market_id
    return result


def batch_analyze(markets: list, max_markets: int = 20, delay: float = 1.0, per_market_timeout: float = 90.0) -> Dict[str, Dict]:
    """
    Analyze a batch of markets.

    Args:
        markets: List of market dicts
        max_markets: Cap to avoid
